import pytest


@pytest.fixture
def hh_api_data() -> dict:
    return {
        "items": [
            {'id': '120379473',
             'premium': False,
             'name': 'Инженер по тестированию (ручное тестирование)',
             'department': None,
             'has_test': True,
             'response_letter_required': True,
             'area':
                 {'id': '88',
                  'name': 'Казань',
                  'url': 'https://api.hh.ru/areas/88'},
             'salary':
                 {'from': 80000,
                  'to': 100000,
                  'currency': 'RUR',
                  'gross': False},
             'salary_range':
                 {'from': 80000,
                  'to': 100000,
                  'currency': 'RUR',
                  'gross': False,
                  'mode': {
                      'id': 'MONTH',
                      'name': 'За\xa0месяц'
                  },
                  'frequency': None},
             'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None,
             'sort_point_distance': None, 'published_at': '2025-05-12T09:26:04+0300',
             'created_at': '2025-05-12T09:26:04+0300', 'archived': False,
             'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=120379473',
             'show_logo_in_search': None, 'show_contacts': False, 'insider_interview': None,
             'url': 'https://api.hh.ru/vacancies/120379473?host=hh.ru',
             'alternate_url': 'https://hh.ru/vacancy/120379473', 'relations': [],
             'employer': {'id': '10246537', 'name': 'Кибертех', 'url': 'https://api.hh.ru/employers/10246537',
                          'alternate_url': 'https://hh.ru/employer/10246537',
                          'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1230500.png',
                                        '90': 'https://img.hhcdn.ru/employer-logo/6542441.png',
                                        '240': 'https://img.hhcdn.ru/employer-logo/6542442.png'},
                          'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10246537',
                          'accredited_it_employer': True,
                          'employer_rating': {'total_rating': '4.6', 'reviews_count': 3}, 'trusted': True},
             'snippet': {
                 'requirement': 'Знание жизненного цикла программного обеспечения и теории тестирования. Знания <highlighttext>Python</highlighttext>, Pytest, Requests, Selenium, Postman, Swagger. Понимание основ тестирования и владение...',
                 'responsibility': 'Планирование тестирования. Выполнение тестов. Анализ результатов. Сотрудничество с командой. Поддержка качества.'},
             'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [],
             'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
             'fly_in_fly_out_duration': [], 'work_format': [{'id': 'REMOTE', 'name': 'Удалённо'}],
             'working_hours': [{'id': 'HOURS_8', 'name': '8\xa0часов'}],
             'work_schedule_by_days': [{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}], 'night_shifts': False,
             'professional_roles': [{'id': '124', 'name': 'Тестировщик'}], 'accept_incomplete_resumes': False,
             'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
             'employment': {'id': 'full', 'name': 'Полная занятость'},
             'employment_form': {'id': 'FULL', 'name': 'Полная'}, 'internship': False, 'adv_response_url': None,
             'is_adv_vacancy': False, 'adv_context': None},]}


@pytest.fixture
def fake_vacancy_data():
    return {
        "id": "123",
        "name": "Python Developer",
        "alternate_url": "http://example.com/vacancy",
        "salary": {"from": 100000, "to": 150000, "currency": "RUB"},
        "snippet": {"requirement": "Python, Django"},
        "employer": {"name": "Test Company"},
        "area": {"name": "Москва"},
        "employment": {"name": "Полная занятость"},
        "experience": {"name": "От 1 года до 3 лет"},
    }

@pytest.fixture
def hh_api_dates() -> dict:
    """Фикстура"""
    return {
        "items": [
            {
                "id": "120004725",
                "premium": False,
                "name": "Водитель",
                "department": None,
                "has_test": False,
                "response_letter_required": True,
                "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
                "salary": {"from": 5000000, "to": 8000000, "currency": "UZS", "gross": False},
                "salary_range": {
                    "from": 5000000,
                    "to": 8000000,
                    "currency": "UZS",
                    "gross": False,
                    "mode": {"id": "MONTH", "name": "За месяц"},
                    "frequency": {"id": "TWICE_PER_MONTH", "name": "Два раза в месяц"},
                },
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Ташкент",
                    "street": None,
                    "building": None,
                    "lat": 41.2667,
                    "lng": 69.2167,
                    "description": None,
                    "raw": "Ташкент",
                    "metro": None,
                    "metro_stations": [],
                    "id": "18259756",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-04-28T07:54:48+0300",
                "created_at": "2025-04-28T07:54:48+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=120004725",
                "show_contacts": False,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/120004725?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/120004725",
                "relations": [],
                "employer": {
                    "id": "11967213",
                    "name": "YATT SIROTIN DENIS VADIMOVICH",
                    "url": "https://api.hh.ru/employers/11967213",
                    "alternate_url": "https://hh.ru/employer/11967213",
                    "logo_urls": None,
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11967213",
                    "accredited_it_employer": False,
                    "employer_rating": None,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Водительский стаж более 6 лет. Наличие водительского "
                    "удостоверения категории B, C. Ответственность, пунктуальность,"
                    " внимательность. Умение работать с навигационными системами.",
                    "responsibility": "Перевозка грузов по указанным маршрутам. Поддержание "
                    "автомобиля в исправном состоянии. Соблюдение правил "
                    "дорожного движения и техники безопасности. Ведение "
                    "отчетности по...",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": True,
                "fly_in_fly_out_duration": [],
                "work_format": [
                    {"id": "ON_SITE", "name": "На месте работодателя"},
                    {"id": "FIELD_WORK", "name": "Разъездной"},
                ],
                "working_hours": [{"id": "HOURS_8", "name": "8 часов"}],
                "work_schedule_by_days": [
                    {"id": "SIX_ON_ONE_OFF", "name": "6/1"},
                    {"id": "FIVE_ON_TWO_OFF", "name": "5/2"},
                    {"id": "TWO_ON_TWO_OFF", "name": "2/2"},
                ],
                "night_shifts": False,
                "professional_roles": [{"id": "21", "name": "Водитель"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "moreThan6", "name": "Более 6 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": True,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "119920638",
                "premium": False,
                "name": "Ученик флориста",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
                "salary": None,
                "salary_range": {
                    "from": 5000000,
                    "to": 8000000,
                    "currency": "UZS",
                    "gross": False,
                    "mode": {"id": "MONTH", "name": "За месяц"},
                    "frequency": {"id": "TWICE_PER_MONTH", "name": "Два раза в месяц"},
                },
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-04-24T15:27:49+0300",
                "created_at": "2025-04-24T15:27:49+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=119920638",
                "show_logo_in_search": None,
                "show_contacts": False,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/119920638?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/119920638",
                "relations": [],
                "employer": {
                    "id": "10480966",
                    "name": "Studio Nargiz balloons&Flowers",
                    "url": "https://api.hh.ru/employers/10480966",
                    "alternate_url": "https://hh.ru/employer/10480966",
                    "logo_urls": {
                        "original": "https://img.hhcdn.ru/employer-logo-original/1416527.png",
                        "90": "https://img.hhcdn.ru/employer-logo/7285757.png",
                        "240": "https://img.hhcdn.ru/employer-logo/7285758.png",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=10480966",
                    "accredited_it_employer": False,
                    "employer_rating": None,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Ты будешь учиться и сразу применять знания на практике: "
                    "помогать в сборке букетов, ухаживать за цветами, оформлять "
                    "витрины. ",
                    "responsibility": None,
                },
                "contacts": None,
                "schedule": {"id": "flexible", "name": "Гибкий график"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "fly_in_fly_out_duration": [],
                "work_format": [{"id": "ON_SITE", "name": "На месте работодателя"}],
                "working_hours": [{"id": "FLEXIBLE", "name": "По договорённости"}],
                "work_schedule_by_days": [{"id": "OTHER", "name": "Другое"}],
                "night_shifts": True,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
        ]
    }